name: alfredomoramanzano
favicon: null
layout_spectrum: 0.1672210854012519
typography_spectrum: 0.10677122045308352
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.03243888053111732
  lightness: 0.6508088631089777
  saturation: 0.9800257398746908
  rhythmicContrast: 0.7771168421022594
purpose: []
