name: alfredomoramanzano
favicon: null
layout_spectrum: 0.49861
typography_spectrum: 0.63186
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#b9b9b9'
    - '#979797'
    - '#585858'
  brandStrength: 0.4375
  lightness: 0.8125
  saturation: 0.9800257398746908
  rhythmicContrast: 0.7771168421022594
purpose: []
