name: alfredomoramanzano
favicon: null
layout_spectrum: 0.23957
typography_spectrum: 0.93058
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#b9b9b9'
    - '#979797'
    - '#585858'
  brandStrength: 0.125
  lightness: 1
  saturation: 0.9800257398746908
  rhythmicContrast: 0.25
purpose: []
