typography_spectrum: 0
color:
  brandColors:
    - '#1b1b1b'
    - '#ffffff'
    - '#575757'
    - '#afafaf'
    - '#858585'
  brandStrength: 0.75
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75065
analytics:
  google: null
  facebook: null
  twitter: null
name: alfredomoramanzano
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Alfredo Mora Manzano
description: "TV era mi heroína, Internet es mi Metadona...\_"
purpose: []
