name: alfredomoramanzano
favicon: null
layout_spectrum: 0.49861
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1b1b'
    - '#ffffff'
    - '#575757'
    - '#afafaf'
    - '#858585'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
